### ISSUE TITLE
module edition

### ISSUE THREAD

**Issue by CCZU-ZH** [JNAIC/PIPMN#4]
what python and torch versions are used in your code, or give a list of packages like requirements。

**Comment by dongdongunique** [comment]
Thanks for your advise, the python version is 3.9.7 and the torch version is 1.13.1+cu116

**Comment by CCZU-ZH** [comment]
您好，我在debug‘train_and_eval.py’的时候，运行到def train(data_path,random_state=42,epoches=3500,weight_decay=0.05,label_smoothing=0.1):这行代码时候自动跳出了，也没有报错。想请问下是什么原因，会不会是我安装的包不匹配。可以请您帮忙看一下吗？
这是我的运行图片
![1718347893013](https://github.com/JNAIC/PIPMN/assets/153486776/f7cf153b-f3d9-432a-b944-9590c464dd06)
如果需要可以查看附件requirements
[requirements.txt](https://github.com/user-attachments/files/15833011/requirements.txt)

**Comment by dongdongunique** [comment]
大哥你都没有调用这个函数，别说debug了，运行都运行不了的

**Comment by dongdongunique** [comment]
你可以使用 ![image](https://github.com/JNAIC/PIPMN/assets/89110975/cd872ecb-b417-47c3-88c9-220cd6c198b1)', 然后调用这个函数

**Comment by CCZU-ZH** [comment]
谢谢提醒，我试试看

**Comment by CCZU-ZH** [comment]
谢谢提醒，我试试看，那外面的那个main_model.py有用吗

**Comment by dongdongunique** [comment]
你可以不用那个东西的；

**Comment by dongdongunique** [comment]
兄弟如果你用我的代码的话，别忘了引用我的文章哦

**Comment by CCZU-ZH** [comment]
那必须必啊，要是能用这个代码迁移到我的东西上面，我论文都可以带个你呀

**Comment by dongdongunique** [comment]
你的论文我没啥实质贡献，带我倒不用了；如果你觉得代码好用的话，可以多引用引用我的这篇和其他文章（如果内容相关的话）

**Comment by CCZU-ZH** [comment]
要是代码方面我不会的问你，你愿意花时间回答就有了。

**Comment by CCZU-ZH** [comment]
哥，可以给个联系方式不，又遇到问题了。

**Comment by CCZU-ZH** [comment]
![1718347893013](https://github.com/JNAIC/PIPMN/assets/153486776/f880a0f8-5d27-43f8-af30-d03cfebffafb)

**Comment by CCZU-ZH** [comment]
![}FK}XF~28A ~N)4VR}$U4S](https://github.com/JNAIC/PIPMN/assets/153486776/402e937b-972f-4b94-aeaf-b402acc216d3)

**Comment by dongdongunique** [comment]
你微信发一下

**Comment by dongdongunique** [comment]
加好友的时候备注一下学校姓名

**Comment by CCZU-ZH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
